### ISSUE TITLE
Hello, can you do high res for bacon boi blue skin?

### ISSUE THREAD

**Issue by jashin8** [0icj/skins#1]

**Comment by 0icj** [comment]
i saw this just right now in so sorry for seeing this late
will make it when i got home sorry again

**Comment by 0icj** [comment]
https://github.com/0icj/skins/blob/main/Requested.md here
tell me if you want to feedback or smth

**Comment by jashin8** [comment]
no problem, skin is really good, thx

**Comment by jashin8** [comment]
hello again, can you do another hd version of this whitecat skin?
![dc892a81a0db3caf4ebcf86c3a4c0a9c](https://github.com/user-attachments/assets/5e7f370f-bb5c-443b-87a5-b3278ffe97c1)
